/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  setup: () => import("@/views/_builtin/setup/index.vue"),
  admins: () => import("@/views/admins/index.vue"),
  "audit-logs": () => import("@/views/audit-logs/index.vue"),
  backup: () => import("@/views/backup/index.vue"),
  cards: () => import("@/views/cards/index.vue"),
  categories: () => import("@/views/categories/index.vue"),
  coupons: () => import("@/views/coupons/index.vue"),
  docs: () => import("@/views/docs/index.vue"),
  "email-templates": () => import("@/views/email-templates/index.vue"),
  home: () => import("@/views/home/index.vue"),
  jobs: () => import("@/views/jobs/index.vue"),
  "notification-logs": () => import("@/views/notification-logs/index.vue"),
  "order-detail": () => import("@/views/order-detail/index.vue"),
  orders: () => import("@/views/orders/index.vue"),
  "payment-channels": () => import("@/views/payment-channels/index.vue"),
  "product-cards": () => import("@/views/product-cards/index.vue"),
  products: () => import("@/views/products/index.vue"),
  settings: () => import("@/views/settings/index.vue"),
  trash: () => import("@/views/trash/index.vue"),
  uploads: () => import("@/views/uploads/index.vue"),
};
