/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'admins',
    path: '/admins',
    component: 'layout.base$view.admins',
    meta: {
      title: 'admins',
      i18nKey: 'route.admins',
      icon: 'mdi:account-cog-outline',
      order: 8,
      roles: ['owner']
    }
  },
  {
    name: 'audit-logs',
    path: '/audit-logs',
    component: 'layout.base$view.audit-logs',
    meta: {
      title: 'audit-logs',
      i18nKey: 'route.audit-logs',
      icon: 'mdi:file-document-outline',
      order: 12,
      roles: ['owner']
    }
  },
  {
    name: 'backup',
    path: '/backup',
    component: 'layout.base$view.backup',
    meta: {
      title: 'backup',
      i18nKey: 'route.backup',
      icon: 'mdi:database-export-outline',
      order: 15,
      roles: ['owner']
    }
  },
  {
    name: 'cards',
    path: '/cards',
    component: 'layout.base$view.cards',
    meta: {
      title: 'cards',
      i18nKey: 'route.cards',
      icon: 'mdi:credit-card-multiple-outline',
      order: 4
    }
  },
  {
    name: 'categories',
    path: '/categories',
    component: 'layout.base$view.categories',
    meta: {
      title: 'categories',
      i18nKey: 'route.categories',
      icon: 'mdi:tag-multiple-outline',
      order: 4
    }
  },
  {
    name: 'coupons',
    path: '/coupons',
    component: 'layout.base$view.coupons',
    meta: {
      title: 'coupons',
      i18nKey: 'route.coupons',
      icon: 'mdi:ticket-percent-outline',
      order: 5
    }
  },
  {
    name: 'docs',
    path: '/docs',
    component: 'layout.base$view.docs',
    meta: {
      title: 'docs',
      i18nKey: 'route.docs',
      icon: 'mdi:book-open-page-variant-outline',
      order: 16
    }
  },
  {
    name: 'email-templates',
    path: '/email-templates',
    component: 'layout.base$view.email-templates',
    meta: {
      title: 'email-templates',
      i18nKey: 'route.email-templates',
      icon: 'mdi:email-outline',
      order: 7
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'jobs',
    path: '/jobs',
    component: 'layout.base$view.jobs',
    meta: {
      title: 'jobs',
      i18nKey: 'route.jobs',
      icon: 'mdi:cog-sync-outline',
      order: 10
    }
  },
  {
    name: 'login',
    path: '/login',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'notification-logs',
    path: '/notification-logs',
    component: 'layout.base$view.notification-logs',
    meta: {
      title: 'notification-logs',
      i18nKey: 'route.notification-logs',
      icon: 'mdi:bell-outline',
      order: 11
    }
  },
  {
    name: 'order-detail',
    path: '/orders/:id',
    component: 'layout.base$view.order-detail',
    props: true,
    meta: {
      title: 'order-detail',
      i18nKey: 'route.order-detail',
      hideInMenu: true,
      activeMenu: 'orders'
    }
  },
  {
    name: 'orders',
    path: '/orders',
    component: 'layout.base$view.orders',
    meta: {
      title: 'orders',
      i18nKey: 'route.orders',
      icon: 'mdi:cart-outline',
      order: 2
    },
    props: true
  },
  {
    name: 'payment-channels',
    path: '/payment-channels',
    component: 'layout.base$view.payment-channels',
    meta: {
      title: 'payment-channels',
      i18nKey: 'route.payment-channels',
      icon: 'mdi:credit-card-outline',
      order: 6
    }
  },
  {
    name: 'product-cards',
    path: '/products/:id/cards',
    component: 'layout.base$view.product-cards',
    props: true,
    meta: {
      title: 'product-cards',
      i18nKey: 'route.product-cards',
      hideInMenu: true,
      activeMenu: 'products'
    }
  },
  {
    name: 'products',
    path: '/products',
    component: 'layout.base$view.products',
    meta: {
      title: 'products',
      i18nKey: 'route.products',
      icon: 'mdi:package-variant',
      order: 3
    }
  },
  {
    name: 'settings',
    path: '/settings',
    component: 'layout.base$view.settings',
    meta: {
      title: 'settings',
      i18nKey: 'route.settings',
      icon: 'mdi:cog-outline',
      order: 9,
      roles: ['owner']
    }
  },
  {
    name: 'setup',
    path: '/setup',
    component: 'layout.blank$view.setup',
    meta: {
      title: 'setup',
      i18nKey: 'route.setup',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'trash',
    path: '/trash',
    component: 'layout.base$view.trash',
    meta: {
      title: 'trash',
      i18nKey: 'route.trash',
      icon: 'mdi:delete-outline',
      order: 13
    }
  },
  {
    name: 'uploads',
    path: '/uploads',
    component: 'layout.base$view.uploads',
    meta: {
      title: 'uploads',
      i18nKey: 'route.uploads',
      icon: 'mdi:image-multiple-outline',
      order: 14
    }
  }
];
